apiVersion: v1
kind: Secret
metadata:
    name: super-secret
data:
    pass: ENC[AES256_GCM,data:GJuM5h4uNac=,iv:t1XV+RtxHe0ok/+mWWooTCV/+KHv1/6thmJ8SnnSPAE=,tag:dApsY6LW5Ae37IItnheFYw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:930574414246:key/a1c83598-eb09-4e62-994c-7859f81c7e9d
          created_at: "2021-09-23T11:44:00Z"
          enc: AQICAHhx7ygKxFXkvpLCdl5qY7brRlviJXOORg9r6LjRsE0sZQHzZ4cdOKawSjAmnuPKCDYMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMExo+MPB/NTn+5W8aAgEQgDupzdhg/1x7mkqQqy6Fz9wA9cnTJz/2FNizY1CFOTyPiOKXODYnc1iW0zA1+WfORWDgDX8uEC+c3/F8MQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-23T11:44:02Z"
    mac: ENC[AES256_GCM,data:/iLfuShJy0LGJcnHPLYZubNG9AtO9NV20HVFl7ZNBeOcj7CIt5PftXqrlD7n7jusmHO0R8LBxQyBqY4zgvCvdojrzgtSiXE3gP2bONMn5Dp8GiEh3RNERusAdfBFdPa5ewGU0iJoebiwU3NmM5MIBIVq6lcO+nJlHQCo/c7oOJ0=,iv:bk6OY6VUbc/vbGdl+Uo/TZmf1CmFMk4HZBidupuJV/8=,tag:caUJFGaij3bw5Cd2kTYAgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
