apiVersion: v1
kind: Secret
metadata:
    name: super-secret
stringData:
    password: ENC[AES256_GCM,data:2v3WVqAI8I47+5R/zEJ08rhPuApa,iv:t6qy8CuG9hSeC0spnHvtrbRhWCHgI7k/OkxAYLwf6Hc=,tag:4dn1GPwRzAV0Dvi8yuHDDw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:930574414246:key/9e06a9a7-7eb1-4ba8-a914-70f632fa6af3
          created_at: "2021-09-29T16:15:30Z"
          enc: AQICAHjJAOFgepyA5wq3/KcT58D1ZGZNt8XVnDZx+kvI7HiOjwF4Qn8vY8isPMhi3aIrqc7KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzX6qhMwyRoPLbcFLAgEQgDsIco/o2Hg64J2ytrsKUIV/Lp9pZDj9rG1UJCxJNYuP2glGKUzdfmqKy/I1wic/UXN3HgksJ1hdAmGXSw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-29T16:15:31Z"
    mac: ENC[AES256_GCM,data:AePVFkaFCnPfpnEE/CIDxp+/GwZsYtqVztgeRfxtqszweNstjmb0gk+VgP/Q9+OuR1cSMhuZaav8Y7KpO1hNxGRO0ry5mvKEk11gSGh0qv5drs0qj9Ce7P56e+itUOpzkviqvre8EzeZqUOKLPJyELbzrElV2htV3TPLnQQFok8=,iv:vurAWyLpPUuF3g9xr/8ta9HB5gdckjqol5Eg7o66Ikg=,tag:6uBIo4RYGL/oo4F2Ks9QbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
